// Code generated by MockGen. DO NOT EDIT.
// Source: rabbitmq.go
//
// Generated by this command:
//
//	mockgen -package=repomock -source=rabbitmq.go -destination=../../../mock/repository/rabbitmq.go
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRabbitMQRepo is a mock of RabbitMQRepo interface.
type MockRabbitMQRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitMQRepoMockRecorder
	isgomock struct{}
}

// MockRabbitMQRepoMockRecorder is the mock recorder for MockRabbitMQRepo.
type MockRabbitMQRepoMockRecorder struct {
	mock *MockRabbitMQRepo
}

// NewMockRabbitMQRepo creates a new mock instance.
func NewMockRabbitMQRepo(ctrl *gomock.Controller) *MockRabbitMQRepo {
	mock := &MockRabbitMQRepo{ctrl: ctrl}
	mock.recorder = &MockRabbitMQRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitMQRepo) EXPECT() *MockRabbitMQRepoMockRecorder {
	return m.recorder
}

// PushPowerMeter mocks base method.
func (m *MockRabbitMQRepo) PushPowerMeter(ctx context.Context, msgBody []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushPowerMeter", ctx, msgBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushPowerMeter indicates an expected call of PushPowerMeter.
func (mr *MockRabbitMQRepoMockRecorder) PushPowerMeter(ctx, msgBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushPowerMeter", reflect.TypeOf((*MockRabbitMQRepo)(nil).PushPowerMeter), ctx, msgBody)
}
