// Code generated by MockGen. DO NOT EDIT.
// Source: timescale.go
//
// Generated by this command:
//
//	mockgen -package=repomock -source=timescale.go -destination=../../../mock/repository/timescale.go
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	modelPostgresql "github.com/alhamsya/voltron/internal/core/domain/postgresql"
	modelPower "github.com/alhamsya/voltron/internal/core/domain/power"
	modelRequest "github.com/alhamsya/voltron/internal/core/domain/request"
	gomock "go.uber.org/mock/gomock"
)

// MockTimescaleRepo is a mock of TimescaleRepo interface.
type MockTimescaleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTimescaleRepoMockRecorder
	isgomock struct{}
}

// MockTimescaleRepoMockRecorder is the mock recorder for MockTimescaleRepo.
type MockTimescaleRepoMockRecorder struct {
	mock *MockTimescaleRepo
}

// NewMockTimescaleRepo creates a new mock instance.
func NewMockTimescaleRepo(ctrl *gomock.Controller) *MockTimescaleRepo {
	mock := &MockTimescaleRepo{ctrl: ctrl}
	mock.recorder = &MockTimescaleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimescaleRepo) EXPECT() *MockTimescaleRepoMockRecorder {
	return m.recorder
}

// BulkPowerMeter mocks base method.
func (m *MockTimescaleRepo) BulkPowerMeter(ctx context.Context, param []modelPostgresql.PowerMeter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkPowerMeter", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkPowerMeter indicates an expected call of BulkPowerMeter.
func (mr *MockTimescaleRepoMockRecorder) BulkPowerMeter(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkPowerMeter", reflect.TypeOf((*MockTimescaleRepo)(nil).BulkPowerMeter), ctx, param)
}

// GetBillingSummary mocks base method.
func (m *MockTimescaleRepo) GetBillingSummary(ctx context.Context, deviceID string, from, to time.Time) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillingSummary", ctx, deviceID, from, to)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillingSummary indicates an expected call of GetBillingSummary.
func (mr *MockTimescaleRepoMockRecorder) GetBillingSummary(ctx, deviceID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillingSummary", reflect.TypeOf((*MockTimescaleRepo)(nil).GetBillingSummary), ctx, deviceID, from, to)
}

// GetDailyUsageLines mocks base method.
func (m *MockTimescaleRepo) GetDailyUsageLines(ctx context.Context, deviceID string, from, to time.Time) ([]modelPower.DailyLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyUsageLines", ctx, deviceID, from, to)
	ret0, _ := ret[0].([]modelPower.DailyLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyUsageLines indicates an expected call of GetDailyUsageLines.
func (mr *MockTimescaleRepoMockRecorder) GetDailyUsageLines(ctx, deviceID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyUsageLines", reflect.TypeOf((*MockTimescaleRepo)(nil).GetDailyUsageLines), ctx, deviceID, from, to)
}

// GetMeterDailyUsage mocks base method.
func (m *MockTimescaleRepo) GetMeterDailyUsage(ctx context.Context, deviceID string, from, to time.Time) ([]modelPostgresql.DailyUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeterDailyUsage", ctx, deviceID, from, to)
	ret0, _ := ret[0].([]modelPostgresql.DailyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeterDailyUsage indicates an expected call of GetMeterDailyUsage.
func (mr *MockTimescaleRepoMockRecorder) GetMeterDailyUsage(ctx, deviceID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeterDailyUsage", reflect.TypeOf((*MockTimescaleRepo)(nil).GetMeterDailyUsage), ctx, deviceID, from, to)
}

// GetMeterLatestMeter mocks base method.
func (m *MockTimescaleRepo) GetMeterLatestMeter(ctx context.Context, deviceID string) ([]modelPostgresql.Latest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeterLatestMeter", ctx, deviceID)
	ret0, _ := ret[0].([]modelPostgresql.Latest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeterLatestMeter indicates an expected call of GetMeterLatestMeter.
func (mr *MockTimescaleRepoMockRecorder) GetMeterLatestMeter(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeterLatestMeter", reflect.TypeOf((*MockTimescaleRepo)(nil).GetMeterLatestMeter), ctx, deviceID)
}

// GetMeterTimeSeries mocks base method.
func (m *MockTimescaleRepo) GetMeterTimeSeries(ctx context.Context, param *modelRequest.TimeSeries) ([]modelPostgresql.PowerMeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeterTimeSeries", ctx, param)
	ret0, _ := ret[0].([]modelPostgresql.PowerMeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeterTimeSeries indicates an expected call of GetMeterTimeSeries.
func (mr *MockTimescaleRepoMockRecorder) GetMeterTimeSeries(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeterTimeSeries", reflect.TypeOf((*MockTimescaleRepo)(nil).GetMeterTimeSeries), ctx, param)
}
