// Code generated by MockGen. DO NOT EDIT.
// Source: meter.go
//
// Generated by this command:
//
//	mockgen -package=usecasemock -source=meter.go -destination=../../mock/usecase/meter.go
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	modelRequest "github.com/alhamsya/voltron/internal/core/domain/request"
	modelResponse "github.com/alhamsya/voltron/internal/core/domain/response"
	gomock "go.uber.org/mock/gomock"
)

// MockMeterService is a mock of MeterService interface.
type MockMeterService struct {
	ctrl     *gomock.Controller
	recorder *MockMeterServiceMockRecorder
	isgomock struct{}
}

// MockMeterServiceMockRecorder is the mock recorder for MockMeterService.
type MockMeterServiceMockRecorder struct {
	mock *MockMeterService
}

// NewMockMeterService creates a new mock instance.
func NewMockMeterService(ctrl *gomock.Controller) *MockMeterService {
	mock := &MockMeterService{ctrl: ctrl}
	mock.recorder = &MockMeterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterService) EXPECT() *MockMeterServiceMockRecorder {
	return m.recorder
}

// Latest mocks base method.
func (m *MockMeterService) Latest(ctx context.Context, deviceID string) (modelResponse.Common, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx, deviceID)
	ret0, _ := ret[0].(modelResponse.Common)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockMeterServiceMockRecorder) Latest(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockMeterService)(nil).Latest), ctx, deviceID)
}

// LogPowerMeter mocks base method.
func (m *MockMeterService) LogPowerMeter(ctx context.Context, param []modelRequest.PowerMater) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPowerMeter", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogPowerMeter indicates an expected call of LogPowerMeter.
func (mr *MockMeterServiceMockRecorder) LogPowerMeter(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPowerMeter", reflect.TypeOf((*MockMeterService)(nil).LogPowerMeter), ctx, param)
}

// Reading mocks base method.
func (m *MockMeterService) Reading(ctx context.Context, param []modelRequest.PowerMater) (modelResponse.Common, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reading", ctx, param)
	ret0, _ := ret[0].(modelResponse.Common)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reading indicates an expected call of Reading.
func (mr *MockMeterServiceMockRecorder) Reading(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reading", reflect.TypeOf((*MockMeterService)(nil).Reading), ctx, param)
}

// TimeSeries mocks base method.
func (m *MockMeterService) TimeSeries(ctx context.Context, param *modelRequest.TimeSeries) (modelResponse.Common, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeSeries", ctx, param)
	ret0, _ := ret[0].(modelResponse.Common)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimeSeries indicates an expected call of TimeSeries.
func (mr *MockMeterServiceMockRecorder) TimeSeries(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeSeries", reflect.TypeOf((*MockMeterService)(nil).TimeSeries), ctx, param)
}
